spring.application.name=spotify-backend

# Porta do Servidor
server.port=8080

# Importa o arquivo de segredos se ele existir localmente (ignorado no GitHub)
spring.config.import=optional:classpath:application-secret.properties

# Configuracoes de Banco de Dados (PostgreSQL no Neon.tech)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Variavel JWT Secreta
api.security.token.secret=${JWT_SECRET}

# Configuracoes do Redis (Upstash)
spring.data.redis.url=${REDIS_URL}
